Repository TriauNicolas/SQLizer-back, pull requests merged in 2023-10, with the labels that each got.

#8 changes-dockerisation - online deployment
  .env.proto
  docker-compose.yml
Labels: enhancement

#9 Ft/single user db update
  db/init.sql
  prisma/schema.prisma
  src/controllers/databases.controllers.ts
  src/index.ts
  src/models/models.d.ts
  src/routes/databases.routes.ts
Labels: enhancement

#10 Fix: add firstName, lastName and email on login response
  src/controllers/authentication.controllers.ts
Labels: enhancement

#15 Feat: Sockets
  README.md
  docker-compose.yml
  insomnia_documentation.json
  package-lock.json
  package.json
  src/controllers/authentication.controllers.ts
  src/controllers/canvas.controllers.ts
  src/controllers/databases.controllers.ts
  src/core/sockets.ts
  src/index.ts
  src/models/models.d.ts
Labels: enhancement

#17 Fix: lastName not saved
  src/controllers/authentication.controllers.ts
Labels: bug

#18 Ft: add deployment requirements
  docker-compose.yml
  start
Labels: enhancement

#16 Ft/extract logic services
  src/controllers/authentication.controllers.ts
  src/controllers/canvas.controllers.ts
  src/controllers/databases.controllers.ts
  src/controllers/workgroups.controllers.ts
  src/models/models.d.ts
  src/services/authentication.services.ts
  src/services/databases.services.ts
  src/services/databasesGroups.services.ts
  src/services/usersWorkgroups.services.ts
  src/services/workgroups.services.ts
Labels: enhancement

#20 User Accessing DB
  src/controllers/authentication.controllers.ts
  src/controllers/canvas.controllers.ts
  src/routes/authentication.routes.ts
Labels: bug, enhancement

#13 Feat: add route to get datas about workgroups
  src/controllers/workgroups.controllers.ts
  src/routes/workgroups.routes.ts
  src/services/usersWorkgroups.services.ts
Labels: enhancement
